org: egestudent

service: mixy

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  iam:
    role: arn:aws:iam::586794471369:role/serverless
  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS

package:
  individually: true
  excludeDevDependencies: true

functions:
  userSignUp:
    handler: src/backend/functions/userSignup/index.handler
    events:
      - httpApi:
          path: /signup
          method: post
  userLogin:
    handler: src/backend/functions/userLogin/index.handler
    events:
      - httpApi:
          path: /login
          method: post
  dailyWord:
    handler: src/backend/functions/dailyWord/index.handler
    events:
      - httpApi:
          path: /dailyword
          method: get

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    DailyWord:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DailyWord
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
